🐛 Improves Shell Profile Startup Resilience
This helps to address some cases where the profile has been partially (or completely) run already, and then the user tries to run it again.

Conversely, this also helps address some cases where the profile startup process is being entered "mid-way" through, and we need to go run the "earlier" parts first.

diff --git a/shell/bash_profile b/shell/bash_profile
--- a/shell/bash_profile
+++ b/shell/bash_profile
@@ -2,27 +2,46 @@
 
 
 cd ~/.dotfiles/shell &> /dev/null || return 0
-profile_hook_exit_code=0
+
+export PROFILE_STAGE
+PROFILE_STAGE="bash➡️env"; profile_hook_exit_code=0
 source init.sh "bash" "env" || profile_hook_exit_code=$?
-if [ ! $profile_hook_exit_code -eq 0 ]; then
+if [ "$profile_hook_exit_code" -ne 0 ]; then
     cd ~ &> /dev/null
     echo "[bash|env] Profile hook failed, returned code '$profile_hook_exit_code'. (bash_profile)" >&2
     unset profile_hook_exit_code
+    PROFILE_STAGE="bash@env❌"
     return 0
+else
+    PROFILE_STAGE="bash@env✅"
 fi
 
-source init.sh "bash" "login" || profile_hook_exit_code=$?
-if [ ! $profile_hook_exit_code -eq 0 ]; then
+if [ "$PROFILE_STAGE" = "bash@env✅" ]; then
+    PROFILE_STAGE="bash➡️login"; profile_hook_exit_code=0
+    source init.sh "bash" "login" || profile_hook_exit_code=$?
+    if [ "$profile_hook_exit_code" -ne 0 ]; then
+        cd ~ &> /dev/null
+        echo "[bash|login] Profile hook failed, returned code '$profile_hook_exit_code'. (bash_profile)" >&2
+        unset profile_hook_exit_code
+        PROFILE_STAGE="bash@login❌"
+        return 0
+    else
+        PROFILE_STAGE="bash@login✅"
+    fi
+fi
+
+if [ "$PROFILE_STAGE" = "bash@login✅" ]; then
+    PROFILE_STAGE="bash➡️rc"; profile_hook_exit_code=0
+    source init.sh "bash" "rc" || profile_hook_exit_code=$?
     cd ~ &> /dev/null
-    echo "[bash|login] Profile hook failed, returned code '$profile_hook_exit_code'. (bash_profile)" >&2
-    unset profile_hook_exit_code
-    return 0
+    if [ ! $profile_hook_exit_code -eq 0 ]; then
+        echo "[bash|rc] Profile hook failed, returned code '$profile_hook_exit_code'.  (bash_profile)" >&2
+        unset profile_hook_exit_code
+        PROFILE_STAGE="bash@rc❌"
+        return 0
+    else
+        PROFILE_STAGE="bash@rc✅"
+    fi
 fi
 
-source init.sh "bash" "rc" || profile_hook_exit_code=$?
 cd ~ &> /dev/null
-if [ ! $profile_hook_exit_code -eq 0 ]; then
-    echo "[bash|rc] Profile hook failed, returned code '$profile_hook_exit_code'. (bash_profile)" >&2
-    unset profile_hook_exit_code
-    return 0
-fi
diff --git a/shell/zshrc b/shell/zshrc
--- a/shell/zshrc
+++ b/shell/zshrc
@@ -2,10 +2,48 @@
 
 
 cd ~/.dotfiles/shell &> /dev/null || return 0
-local profile_hook_exit_code=0
-source init.sh "zsh" "rc" || profile_hook_exit_code=$?
-cd ~ &> /dev/null
-if [ ! $profile_hook_exit_code -eq 0 ]; then
-    echo "[zsh|rc] Profile hook failed, returned code '$profile_hook_exit_code'." >&2
-    return 0
+
+if [ -z "$PROFILE_STAGE" ] || [[ ! "$PROFILE_STAGE" =~ ^zsh.* ]]; then
+    export PROFILE_STAGE
+    PROFILE_STAGE="zsh➡️env"; profile_hook_exit_code=0
+    source init.sh "zsh" "env" || profile_hook_exit_code=$?
+    if [ "$profile_hook_exit_code" -ne 0 ]; then
+        cd ~ &> /dev/null
+        echo "[zsh|env] Profile hook failed, returned code '$profile_hook_exit_code'. (zshrc)" >&2
+        unset profile_hook_exit_code
+        PROFILE_STAGE="zsh@env❌"
+        return 0
+    else
+        PROFILE_STAGE="zsh@env✅"
+    fi
 fi
+
+if [ "$PROFILE_STAGE" = "zsh@env✅" ]; then
+    PROFILE_STAGE="zsh➡️login"; profile_hook_exit_code=0
+    source init.sh "zsh" "login" || profile_hook_exit_code=$?
+    if [ "$profile_hook_exit_code" -ne 0 ]; then
+        cd ~ &> /dev/null
+        echo "[zsh|login] Profile hook failed, returned code '$profile_hook_exit_code'. (zshrc)" >&2
+        unset profile_hook_exit_code
+        PROFILE_STAGE="zsh@login❌"
+        return 0
+    else
+        PROFILE_STAGE="zsh@login✅"
+    fi
+fi
+
+if [ "$PROFILE_STAGE" = "zsh@login✅" ]; then
+    PROFILE_STAGE="zsh➡️rc"; profile_hook_exit_code=0
+    source init.sh "zsh" "rc" || profile_hook_exit_code=$?
+    cd ~ &> /dev/null
+    if [ ! $profile_hook_exit_code -eq 0 ]; then
+        echo "[zsh|rc] Profile hook failed, returned code '$profile_hook_exit_code'.  (zshrc)" >&2
+        unset profile_hook_exit_code
+        PROFILE_STAGE="zsh@rc❌"
+        return 0
+    else
+        PROFILE_STAGE="zsh@rc✅"
+    fi
+fi
+
+cd ~ &> /dev/null
