🏗️ Overhauls Bash/Zsh Profiles
This overhauls the Bash/Zsh profiles so that they have expanded capability while having as much feature parity between Bash and Zsh as reasonably possible. This new design is particularly modular, to make it easy to quickly add new bits of functionality in the future.

The Bash/Zsh profiles are now also somewhat covered with tests, which was a necessary (but fortunate) side-effect of having to iterate on them so heavily as part of this refactor.

diff --git a/shell/bash_profile b/shell/bash_profile
--- a/shell/bash_profile
+++ b/shell/bash_profile
@@ -1,3 +1,28 @@
 #!/usr/bin/env bash
 
-source ~/.dotfiles/shell/bash/_profile.bash
+
+cd ~/.dotfiles/shell &> /dev/null || return 0
+profile_hook_exit_code=0
+source init.sh "bash" "env" || profile_hook_exit_code=$?
+if [ ! $profile_hook_exit_code -eq 0 ]; then
+    cd ~ &> /dev/null
+    echo "[bash|env] Profile hook failed, returned code '$profile_hook_exit_code'. (bash_profile)" >&2
+    unset profile_hook_exit_code
+    return 0
+fi
+
+source init.sh "bash" "login" || profile_hook_exit_code=$?
+if [ ! $profile_hook_exit_code -eq 0 ]; then
+    cd ~ &> /dev/null
+    echo "[bash|login] Profile hook failed, returned code '$profile_hook_exit_code'. (bash_profile)" >&2
+    unset profile_hook_exit_code
+    return 0
+fi
+
+source init.sh "bash" "rc" || profile_hook_exit_code=$?
+cd ~ &> /dev/null
+if [ ! $profile_hook_exit_code -eq 0 ]; then
+    echo "[bash|rc] Profile hook failed, returned code '$profile_hook_exit_code'. (bash_profile)" >&2
+    unset profile_hook_exit_code
+    return 0
+fi
diff --git a/shell/bashrc b/shell/bashrc
--- a/shell/bashrc
+++ b/shell/bashrc
@@ -1,3 +1,12 @@
 #!/usr/bin/env bash
 
-source ~/.dotfiles/shell/bash/_rc.bash
+
+cd ~/.dotfiles/shell &> /dev/null || return 0
+profile_hook_exit_code=0
+source init.sh "bash" "rc" || profile_hook_exit_code=$?
+cd ~ &> /dev/null
+if [ ! $profile_hook_exit_code -eq 0 ]; then
+    echo "[bash|rc] Profile hook failed, returned code '$profile_hook_exit_code'.  (bashrc)" >&2
+    unset profile_hook_exit_code
+    return 0
+fi
diff --git a/shell/zshenv b/shell/zshenv
--- a/shell/zshenv
+++ b/shell/zshenv
@@ -1,3 +1,11 @@
 #!/usr/bin/env zsh
 
-source ~/.dotfiles/shell/zsh/_env.zsh
+
+cd ~/.dotfiles/shell &> /dev/null || return 0
+local profile_hook_exit_code=0
+source init.sh "zsh" "env" || profile_hook_exit_code=$?
+cd ~ &> /dev/null
+if [ ! $profile_hook_exit_code -eq 0 ]; then
+    echo "[zsh|env] Profile hook failed, returned code '$profile_hook_exit_code'. (zshenv)" >&2
+    return 0
+fi
