🐛 Attempts Fix of Execution of .ssh/rc

diff --git a/shell/ssh_rc b/shell/ssh_rc
--- a/shell/ssh_rc
+++ b/shell/ssh_rc
@@ -3,10 +3,12 @@
 
 cd ~/.dotfiles/shell &> /dev/null || return 0
 profile_hook_exit_code=0
-source init.sh "ssh" "rc" || profile_hook_exit_code=$?
+source ./init.sh "ssh" "rc" || profile_hook_exit_code=$?
 cd ~ &> /dev/null
 if [ ! $profile_hook_exit_code -eq 0 ]; then
-    echo "[ssh|rc] Profile hook failed, returned code '$profile_hook_exit_code'. (ssh_rc)" >&2
+    echo "[ssh|rc] Profile hook failed, returned code '$profile_hook_exit_code'.  (sshrc)" >&2
     unset profile_hook_exit_code
     return 0
 fi
+
+cd ~ &> /dev/null
